// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {dnsutil} from '../models';
import {main} from '../models';
import {provider} from '../models';

export function AddAccount(arg1:string,arg2:string,arg3:string,arg4:string):Promise<config.Account>;

export function ChangePin(arg1:string,arg2:string):Promise<void>;

export function CheckZoneNS(arg1:string,arg2:string):Promise<dnsutil.NSCheckResult>;

export function CheckZonesNSBatch(arg1:Array<main.ZoneCheckReq>):Promise<Array<dnsutil.NSCheckResult>>;

export function CreateRecord(arg1:string,arg2:string,arg3:string,arg4:provider.Record):Promise<provider.Record>;

export function DeleteAccount(arg1:string):Promise<void>;

export function DeleteRecord(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function GetAccountDetail(arg1:string):Promise<Record<string, any>>;

export function GetSettings():Promise<config.Settings>;

export function IsPinConfigured():Promise<boolean>;

export function IsUnlocked():Promise<boolean>;

export function ListAccounts():Promise<Array<config.Account>>;

export function ListAllZones():Promise<Array<provider.Zone>>;

export function ListRecords(arg1:string,arg2:string,arg3:string):Promise<Array<provider.Record>>;

export function ListZones(arg1:string):Promise<Array<provider.Zone>>;

export function Lock():Promise<void>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function SetupPin(arg1:string):Promise<void>;

export function TestAccountConnection(arg1:string,arg2:string):Promise<void>;

export function ToggleHideZone(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function UpdateAccount(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UpdateRecord(arg1:string,arg2:string,arg3:string,arg4:provider.Record):Promise<provider.Record>;

export function VerifyPin(arg1:string):Promise<void>;
