// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddAccount'](arg1, arg2, arg3, arg4);
}

export function ChangePin(arg1, arg2) {
  return window['go']['main']['App']['ChangePin'](arg1, arg2);
}

export function CheckZoneNS(arg1, arg2) {
  return window['go']['main']['App']['CheckZoneNS'](arg1, arg2);
}

export function CheckZonesNSBatch(arg1) {
  return window['go']['main']['App']['CheckZonesNSBatch'](arg1);
}

export function CreateRecord(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateRecord'](arg1, arg2, arg3, arg4);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteRecord(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteRecord'](arg1, arg2, arg3, arg4);
}

export function GetAccountDetail(arg1) {
  return window['go']['main']['App']['GetAccountDetail'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function IsPinConfigured() {
  return window['go']['main']['App']['IsPinConfigured']();
}

export function IsUnlocked() {
  return window['go']['main']['App']['IsUnlocked']();
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function ListAllZones() {
  return window['go']['main']['App']['ListAllZones']();
}

export function ListRecords(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListRecords'](arg1, arg2, arg3);
}

export function ListZones(arg1) {
  return window['go']['main']['App']['ListZones'](arg1);
}

export function Lock() {
  return window['go']['main']['App']['Lock']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetupPin(arg1) {
  return window['go']['main']['App']['SetupPin'](arg1);
}

export function TestAccountConnection(arg1, arg2) {
  return window['go']['main']['App']['TestAccountConnection'](arg1, arg2);
}

export function ToggleHideZone(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleHideZone'](arg1, arg2, arg3);
}

export function UpdateAccount(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateAccount'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateRecord(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateRecord'](arg1, arg2, arg3, arg4);
}

export function VerifyPin(arg1) {
  return window['go']['main']['App']['VerifyPin'](arg1);
}
